<a href="https://colab.research.google.com/github/lakshanavenkateshan/git-cloud/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a=np.ones((5,5))
b=np.zeros((3,3))
b[1,1]=1
a[1:4,1:4]=b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
a=np.array([[1,2,2,3,44,5],
            [3,4,5,6,10,6]])
sum=np.sum(a,axis=0)
print(sum)

[ 4  6  7  9 54 11]


In [12]:
from google.colab import files
uploaded = files.upload()

Saving arr.txt to arr.txt


In [13]:
arr=np.genfromtxt('arr.txt',delimiter=',')
print(arr)

[[1. 2. 3.]
 [4. 3. 2.]
 [5. 6. 7.]]


In [14]:
import numpy as np
systolic = np.array([120, 140, 130, 150, 110])
diastolic = np.array([80, 90, 85, 95, 70])
print("Systolic:", systolic)
print("Diastolic:", diastolic)
print("Average systolic:", np.mean(systolic))
print("Average diastolic:", np.mean(diastolic))
print("Maximum systolic:", np.max(systolic))
total_pressure = systolic + diastolic
print("Total pressure per patient:", total_pressure)
high_bp = systolic > 130
print("High BP flags:", high_bp)
print("Total high BP patients:", np.sum(high_bp))
max_idx = np.argmax(total_pressure)
print("Patient with highest total pressure is at index:", max_idx)


Systolic: [120 140 130 150 110]
Diastolic: [80 90 85 95 70]
Average systolic: 130.0
Average diastolic: 84.0
Maximum systolic: 150
Total pressure per patient: [200 230 215 245 180]
High BP flags: [False  True False  True False]
Total high BP patients: 2
Patient with highest total pressure is at index: 3


In [17]:
import numpy as np
systolic=np.array([120,100,130,110,150])
diastolic=np.array([80,90,85,75,95])
print("systolic              :",systolic)
print("diastolic             :",diastolic)
print("average systolic      :",np.mean(systolic))
print("average diastolic     :",np.mean(diastolic))
print("maximum systolic      :",np.max(systolic))
print("total_pressure        :",systolic + diastolic)
high_bp=systolic>130
print("high bp flags",high_bp)
print("total high bp patients:",np.sum(high_bp))
max_idx = np.argmax(total_pressure)
print("high pressure index   :", max_idx)

systolic              : [120 100 130 110 150]
diastolic             : [80 90 85 75 95]
average systolic      : 122.0
average diastolic     : 85.0
maximum systolic      : 150
total_pressure        : [200 190 215 185 245]
high bp flags [False False False False  True]
total high bp patients: 1
high pressure index   : 3
